function param = getParam()

param = {...
%     struct('name','0_1_234_CNN_pca100','label_set',{{0,1,[2,3,4]}},'feature',...
%         {{struct('name','CNN/CNN','pca',100,'norm',true)}}),...
%     struct('name','1_234_CNN_pca100','label_set',{{1,[2,3,4]}},'feature',...
%         {{struct('name','CNN/CNN','pca',100,'norm',true)}}),...
%     struct('name','AllCat_Sal_pca50','label_set',{{0,1,2,3,4}},'feature',...
%         {{struct('name','SAL/SAL_16_8','pca',50,'norm',false)}}),...
%     struct('name','AllCat_SalImgCNN_pca100','label_set',{{0,1,2,3,4}},'feature',...
%         {{struct('name','CNN/SalImgCNN','pca',100,'norm',true)}}),...
%     struct('name','AllCat_SalCNN_pca100','label_set',{{0,1,2,3,4}},'feature',...
%         {{struct('name','CNN/SalCNN','pca',100,'norm',true)}}),...
    struct('name','AllCat_CNN_pca100','label_set',{{1,2,3,4}},'feature',...
        {{struct('name','CNN_feat_train','pca',100,'norm',true)}}),...
%     struct('name','AllCat_CNN_SalCNN_pca100','label_set',{{0,1,2,3,4}},'feature',...
%         {{struct('name','CNN/CNN','pca',100,'norm',true),...
%         struct('name','CNN/SalCNN','pca',100,'norm',true)}}),...
%     struct('name','AllCat_CNN_Sal_pca150','label_set',{{0,1,2,3,4}},'feature',...
%         {{struct('name','CNN/CNN','pca',100,'norm',true),...
%         struct('name','SAL/SAL_16_8','pca',50,'norm',false)}}),...
%     struct('name','AllCat_CNN_SalCNN_Sal_pca250','label_set',{{0,1,2,3,4}},'feature',...
%         {{struct('name','CNN/CNN','pca',100,'norm',true),...
%         struct('name','CNN/SalCNN','pca',100,'norm',true),...
%         struct('name','SAL/SAL_16_8','pca',50,'norm',false)}}),...
% %     struct('name','AllCat_GIST_pca100','label_set',{{0,1,2,3,4}},'feature',...
% %         {{struct('name','GIST/GIST_128','pca',100,'norm',false)}}),...
% %     struct('name','AllCat_CNNGIST_pca200n','label_set',{{0,1,2,3,4}},'feature',...
% %         {{struct('name','CNN/CNN','pca',100,'norm',true),...
% %         struct('name','GIST/GIST_128','pca',100,'norm',true)}}),...
% %     struct('name','AllCat_HOG_pca100','label_set',{{0,1,2,3,4}},'feature',...
% %         {{struct('name','HOG/HOG_128','pca',100,'norm',false)}}),...
% %     struct('name','AllCat_SIFT_pca100','label_set',{{0,1,2,3,4}},'feature',...
% %         {{struct('name','SIFT/SIFT_256','pca',100,'norm',false)}}),...
    };