function param = getParam()

param = {...
    struct('name','AllCat_CNN_pca100','label_set',{{0,1,2,3,4}},'feature',...
        {{struct('name','CNN/CNN','pca',100,'norm',true)}}),...
    struct('name','AllCat_GIST_pca100','label_set',{{0,1,2,3,4}},'feature',...
        {{struct('name','GIST/GIST_128','pca',100,'norm',false)}}),...
    struct('name','AllCat_HOG_pca100','label_set',{{0,1,2,3,4}},'feature',...
        {{struct('name','HOG/HOG_128','pca',100,'norm',false)}}),...
    struct('name','AllCat_SIFT_pca100','label_set',{{0,1,2,3,4}},'feature',...
        {{struct('name','SIFT/SIFT_256','pca',100,'norm',false)}}),...
    };