model1 = {...
    struct('name','AIM','printName','AIM','ext','.png','fps',0.14),...
    struct('name','AWS','printName','AWS','ext','.png','fps',0.71),...
    struct('name','CAS','printName','CAS','ext','.png','fps',0.035),...
    struct('name','GBVS','printName','GBVS','ext','.png','fps',1.5),...
    struct('name','HFT','printName','HFT','ext','.png','fps',6.3),...
    struct('name','Itti2','printName','Itti','ext','.png','fps',4.5),...
    struct('name','JuddOrig','printName','Judd','ext','.png','fps',0.067),...
    struct('name','LG','printName','LG','ext','.png','fps',0.087),...
    struct('name','MQDCT','printName','\DeltaQDCT','ext','.png','fps',4.3),...
    struct('name','SigSal','printName','SigSal','ext','.png','fps',30),...
    };
model2 = {...
    struct('name','GBVS','printName','GBVS','ext','.png','fps',1.5),...
    struct('name','Itti2','printName','Itti','ext','.png','fps',4.5),...
    struct('name','JuddOrig','printName','Judd','ext','.png','fps',0.067),...
    struct('name','SigSal','printName','SigSal','ext','.png','fps',30),...
    struct('name','AWS','printName','AWS','ext','.png','fps',0.71),...
    struct('name','BMS_exp_split_labWT','printName','BMS','ext','.png','fps',11),...
    struct('name','BMS_withEdge','printName','BMS+','ext','.png','fps',0.79),...
%     struct('name','SUN','printName','SUN','ext','.png','fps',0.79),...
    };
modelMy = {...
    struct('name','BMS_exp_split_labWT','printName','BMS','ext','.png','fps',11),...
    };
model = [model2];

%     struct('name','BMS','printName','BMS^*','ext','.png','fps',3.5),...,