results = {...
    struct('name','exp2_SalBox_baseline','printName','SO'),...
    struct('name','exp2_EdgeBoxRaw_baseline','printName','EB'),...
    struct('name','exp2_EdgeBox100_baseline','printName','EB+SO'),...
    struct('name','exp2_pred_AllCat_CNN_SalCNN_Sal_pca250_0','printName','EB+SO+BGDet'),...
    struct('name','exp2_Allopt_pred_AllCat_CNN_SalCNN_Sal_pca250_0','printName','EB+SO+BGDet+AllProc'),...
    struct('name','exp2_1opt_pred_AllCat_CNN_SalCNN_Sal_pca250_0','printName','EB+SO+BGDet+SelProc'),...
    struct('name','exp2_gt_pred_AllCat_CNN_SalCNN_Sal_pca250_0','printName','Upper Bound'),...
    };

for i = 1:numel(results)
    load(fullfile('results',results{i}.name));
    %top 1
    fprintf('%s',results{i}.printName);
    fprintf('#1');
    top1 = sum(newR(:,1))/sum(newnInst)
    fprintf('#5');
    top5 = sum(newR(:,5))/sum(newnInst)
    fprintf('#10');
    top10 = sum(newR(:,10))/sum(newnInst)

end