plotDrawStyle={...
    struct('color',[0,162,232]/255,'lineStyle','-'),...%Turquoise
    struct('color',[0,0,0],'lineStyle','-'),...
    struct('color',[0,1,0],'lineStyle','-'),...
    struct('color',[1,0,0],'lineStyle','-'),...
    struct('color',[163,73,164]/255,'lineStyle','--'),...%purple    %%%%%%%%%%%%%%%%%%%%
    struct('color',[0,0,1],'lineStyle','-'),...
    struct('color',[0,0,1],'lineStyle','-.'),...
    struct('color',[255,127,39]/255,'lineStyle','-.'),...%orange
    struct('color',[136,0,21]/255,'lineStyle','--'),...%dark red
    struct('color',[255,127,39]/255,'lineStyle','-.'),...%orange
    };
results = {...
    struct('name','exp2_SalBox_baseline','printName','SO'),...
    struct('name','exp2_EdgeBoxRaw_baseline','printName','EB'),...
%     struct('name','exp2_EdgeBox100_baseline','printName','EB+SO'),...
%     struct('name','exp2_pred_AllCat_CNN_SalCNN_Sal_pca250_0','printName','EB+SO+BGDet'),...
%     struct('name','exp2_Allopt_pred_AllCat_CNN_SalCNN_Sal_pca250_0','printName','EB+SO+BGDet+AllProc'),...
%     struct('name','exp2_1opt_pred_AllCat_CNN_SalCNN_Sal_pca250_0','printName','EB+SO+BGDet+SelProc'),...
%     struct('name','exp2_gt_pred_AllCat_CNN_SalCNN_Sal_pca250_0','printName','Upper Bound'),...
    };
% close all;

figure, hold on
name = {};
for i=1:numel(results)
    load(fullfile('results',results{i}.name));
    plot(sum(newR)/sum(newnInst),sum(newR)./sum(newnProp),...
        'color',plotDrawStyle{i}.color,'lineStyle',plotDrawStyle{i}.lineStyle,'linewidth',2);
    name{i} = results{i}.printName;
end
grid on
axis([0.2 1 0 0.52]);
legend(name)